/**
 * Endonyms (native language names) used to show "native — English" in dropdowns.
 * Keys are the language codes we store (ISO-ish). Region variants fall back to base.
 */
export const LANGUAGE_ENDONYMS: Record<string, string> = {
  multi: "Multilingual",
  af: "Afrikaans",
  am: "አማርኛ",
  ar: "العربية",
  as: "অসমীয়া",
  az: "Azərbaycan",
  ba: "Башҡорт",
  be: "Беларуская",
  bg: "Български",
  bn: "বাংলা",
  bo: "བོད་སྐད",
  br: "Brezhoneg",
  bs: "Bosanski",
  ca: "Català",
  cs: "Čeština",
  cy: "Cymraeg",
  da: "Dansk",
  de: "Deutsch",
  el: "Ελληνικά",
  en: "English",
  es: "Español",
  et: "Eesti",
  eu: "Euskara",
  fa: "فارسی",
  fi: "Suomi",
  fo: "Føroyskt",
  fr: "Français",
  gl: "Galego",
  gu: "ગુજરાતી",
  ha: "Hausa",
  haw: "ʻŌlelo Hawaiʻi",
  he: "עברית",
  hi: "हिन्दी",
  hr: "Hrvatski",
  ht: "Kreyòl Ayisyen",
  hu: "Magyar",
  hy: "Հայերեն",
  id: "Bahasa Indonesia",
  is: "Íslenska",
  it: "Italiano",
  ja: "日本語",
  jw: "Basa Jawa",
  ka: "ქართული",
  kk: "Қазақша",
  km: "ខ្មែរ",
  kn: "ಕನ್ನಡ",
  ko: "한국어",
  la: "Latina",
  lb: "Lëtzebuergesch",
  ln: "Lingála",
  lo: "ລາວ",
  lt: "Lietuvių",
  lv: "Latviešu",
  mg: "Malagasy",
  mi: "Māori",
  mk: "Македонски",
  ml: "മലയാളം",
  mn: "Монгол",
  mr: "मराठी",
  ms: "Bahasa Melayu",
  mt: "Malti",
  my: "မြန်မာ",
  ne: "नेपाली",
  nl: "Nederlands",
  nn: "Norsk (Nynorsk)",
  no: "Norsk",
  oc: "Occitan",
  pa: "ਪੰਜਾਬੀ",
  pl: "Polski",
  ps: "پښتو",
  pt: "Português",
  ro: "Română",
  ru: "Русский",
  sa: "संस्कृतम्",
  sd: "سنڌي",
  si: "සිංහල",
  sk: "Slovenčina",
  sl: "Slovenščina",
  sn: "Shona",
  so: "Soomaali",
  sq: "Shqip",
  sr: "Српски",
  su: "Basa Sunda",
  sv: "Svenska",
  sw: "Kiswahili",
  ta: "தமிழ்",
  te: "తెలుగు",
  tg: "Тоҷикӣ",
  th: "ไทย",
  tk: "Türkmen",
  tl: "Tagalog",
  tr: "Türkçe",
  tt: "Татар",
  uk: "Українська",
  ur: "اردو",
  uz: "O‘zbek",
  vi: "Tiếng Việt",
  yi: "ייִדיש",
  yo: "Yorùbá",
  yue: "粵語",
  zh: "中文",
};

export function endonymForLanguageCode(code: string): string | null {
  const raw = String(code || "").trim();
  if (!raw) return null;
  return LANGUAGE_ENDONYMS[raw] ?? LANGUAGE_ENDONYMS[raw.split("-")[0] ?? ""] ?? null;
}

